[project]
name = "url-shortener"
version = "0.1.0"
description = "A simple URL shortener built with Django + DRF"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2,<5.3",
    "djangorestframework>=3.16",
    "psycopg[binary]>=3.2",
    "gunicorn>=23.0",
    "django-environ>=0.12",
    "drf-spectacular>=0.28",
]

[dependency-groups]
dev = [
    "ruff>=0.14",
    "pytest>=8.4",
    "pytest-django>=4.11",
    "mypy>=2.3.1",
    "django-stubs>=6.1.1",
    "djangorestframework-stubs>=3.18.1",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120
target-version = "py313"
extend-exclude = ["*/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "DJ"]


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
pythonpath = ["."]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.13"
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
ignore_missing_imports = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["config.*", "url_shortener.*"]
disallow_untyped_defs = true

[tool.django-stubs]
django_settings_module = "config.settings"